(* Generated by Mirari (Fri, 1 Nov 2013 13:28:01 GMT). *)


let get = function Some x -> x | None -> failwith "Bad IP!"
let ip = `IPv4 (
  get (Ipaddr.V4.of_string "10.0.0.2"),
  get (Ipaddr.V4.of_string "255.255.255.0"),
  [get (Ipaddr.V4.of_string "10.0.0.1")]
)

let main () =
  Net.Manager.create (fun mgr interface id ->
    Net.Manager.configure interface ip >>
    Capture.main mgr interface id
  )

let () = OS.Main.run (Lwt.join [main (); Backend.run ()])
